version: '3'
services:
  jenkins:
    container_name: jenkins-server
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - '$PWD/jenkins-data:/var/jenkins_home'
    networks:
      - net
networks:
  net:
